namespace PasswordlessIdentityServer;

public static class LicenseKey
{
    public const string Licensee = "DEMO"; 

    public const string Key = "eyJhdXRoIjoiREVNTyIsImV4cCI6IjIwMjQtMDktMTJUMDE6MDA6MDEuNTEzMzcwNiswMDowMCIsImlhdCI6IjIwMjQtMDgtMTNUMDE6MDA6MDEiLCJvcmciOiJERU1PIiwiYXVkIjo2fQ==.S7Y3nzzi2Czit59JdBTh9M5y5MKd5LYD53jKEqKFBtgPlYWttdVy2OVSgUXQJjWDQIlWD4DCJnxlXxHdqOqAoM3DTrofJ3KhClyDcFrnyReiTQDxk6aAuwSCuaNeIEtYAG+mWSIc2A9jCvvpgXiDuPXOlaaiuDuihDu0r4IeTfwuOm7HzzoAQCo2b5PyMZuBGamM/PTlcn15X8gLlnHgvdhoDqNy4zJ06FIvrAfhPnu10myNKsHYMCn6EMeuu9w/601QOeQWBThXLcyHx2z0eDEChAmRAuSKASdu63VvVg3L+o/qJBZMHuc4PGtM3ovf9UmfKBu90qTerp7R0S+qr6VL/3sbC7JoUBkcZyici3cEesvOPtoZmGJvhigD6o0Uuk0FachxNNtU3jXyG7tRMXndnS/aOH7f7lVEHQu9SsLKCdaT7wMEIOoOjsdnnyHE7QvN8A8rn4+BGUFFQvMCd/OWXM+rYEVexxMqj8cuLHue9PEVDDYgW+extzb4MBTzak0OVLnstn+Jy2BY7PQRl6efo5R8LdJcWO5rZpjSxGEULFUiAEFfb1Ik0hKap5zCvwGcaKMCVubgkGXtiBVSzVXeB/JFasWYOVwrMw8UyGZ9QkxhTBdZjoXwzU6ZGgpwaa5uHEmn9LCEO7SWGF0V93Z/RIJu3eEYvY/swBCjlBo="; 
}